### ISSUE TITLE
Support recommended store.touch method

### ISSUE THREAD

**Issue by jasonkarns** [balor/connect-memcached#27]
https://github.com/expressjs/session#storetouchsid-session-callback

**Comment by balor** [comment]
Thx for the link.

**Comment by jasonkarns** [comment]
Was `#touch` implemented?

**Comment by atuttle** [comment]
@jasonkarns https://github.com/balor/connect-memcached/commit/6c6ffa42df2cd89da99baee6e80e6da717a0948c

**Comment by sullivanpt** [comment]
By definition "touch" should update the TTL without rewriting the session data.  This implementation is broken, as it just exposes "touch" as a synonym for "set".  This alias approach has an unwanted side effect that it causes session data to be saved on every route, even when the session was unmodified; this particularly troublesome for web apps that have routes purposely built to not modify the session so they can run in parallel.

It would be better to not expose "touch" at all so express-session's built in modification logic will work correctly.

i'm a memcached noob, but digging deeper I noticed that memcached server does implement touch, but it doesn't do so until 1.4.8.  In my anecdotal experience this is too new for many deployments, so fixing "touch" correctly would break this module for many users.

So that leaves a few options for a fix:
- remove the bogus "touch" as "set" alias and update the docs to state touch isn't supported.
- add a flag options.serverSupportsTouch and switch our touch implementation between "touch" or the old "set" behavior dynamically. This is my favorite as it guarantees not breaking anybody that depends on the existing build.
- similar to above but rely on client.version callback to switch implementations. I'm very not fond of this approach because it seems version detection is brittle for customer memcached builds.

Happy to make a PR for your favorite of the above. Thanks.
