### ISSUE TITLE
[Node v8.9.4] Warning: Use Cipheriv for counter mode of aes-256-ctr

### ISSUE THREAD

**Issue by uluru-phatnguyen** [balor/connect-memcached#36]
Hi @balor 

`Warning: Use Cipheriv for counter mode of aes-256-ctr`

Please help us to fix. Thanks.

**Comment by chrisiona** [comment]
I am also noticing this with Node v8.9.4

Taken from [nodejs/node 16746](https://github.com/nodejs/node/issues/16746) 

> It's in the warning: use `crypto.createCipheriv()`, not `crypto.createCipher()`.

I take it we'll need to patch here:
https://github.com/balor/connect-memcached/blob/33f19c21714089c049ba2cdcf2b5094ca51fbb4d/lib/connect-memcached.js#L202

@balor LMK if you'd like a PR

**Comment by balor** [comment]
@chrisiona please do so, it'll definitely motivate me for new minor release :)

**Comment by chrisiona** [comment]
@balor I'll see what I can do.

**Comment by mjamado** [comment]
Any news about this?

**Comment by uluru-phatnguyen** [comment]
@mjamado 
Pls update parse-server 2.8.2
or manual update https://www.npmjs.com/package/@parse/push-adapter

**Comment by balor** [comment]
Ok, found a little time to work on it. 

You get the warning because the default algorithm for crypto is `aes-256-ctr` which is in a counter mode (`-ctr`) and use of these kind of algorithms together with `createCipher` function renders security inefficiency, as the same initialization vector is used every time. To be honest this case shouldn't be possible but somehow node crypto module allowed it and now they're trying to fix broken (cryptographically) code by prompting the warning.

It seems that the reasonable fix is to replace `createCipher` with `createCipheriv` and generate random `iv` each time, but that will **render current session data incompatible**.

Second option is to do a trick similar to [this one](https://github.com/valery-barysok/session-file-store/pull/66/commits/0be22554c159176f41e2f2d10f07c8a4ce74aa19), which tries to differentiate corrupted sessions and use old function on them exclusively. I'm not a big fan of such solutions to be honest.

Finally, if you really want to fix the security problem, you want not only to use new function for but completely replace the session store with properly encoded data.

What do you think? Feedback needed :)

**Comment by balor** [comment]
All right, decided I'll go with the first option, use `createCipheriv` exclusively and bump major version to `1.0.0` as this will be breaking changes.

Concretely, if You're using encryption, after upgrade to `1.0.0` old session data will become unreadable. Positive side of this approach is cleaner code and security consistency on designated session data.

**Comment by mjamado** [comment]
Thanks, @balor! Do you have an estimate as to when it'll land in NPM?

**Comment by balor** [comment]
I'll try to finish everything till the end of this week.

**Comment by balor** [comment]
As promised, [v1.0.0](https://github.com/balor/connect-memcached/releases/tag/v1.0.0) with the changes addressing this issue has been released. Be sure to read the changelog.
